GRID_HEIGHT = 20
GRID_WIDTH = 30

ROBOT_SENSOR_RANGE = 2

UNKNOWN = -1
FREE = 0
OBSTACLE = 1
VICTIM = 2

ROBOT_START = (17, 2)
VICTIM_POSITION = (2, 27)

DRONE_SENSOR_RANGE = 5
DRONE_DEPLOY_STEP = 10

DRONE_CRUISE_ALTITUDE = 5.0
DRONE_VERTICAL_SPEED = 1.0
DRONE_CLEARANCE = 1.0
DRONE_SCAN_STEPS = 2
