MAP_FILE = "maps/map1.txt"

# cell values
UNKNOWN = -1
FREE = 0
OBSTACLE = 1
VICTIM = 2

# ground robot
ROBOT_SENSOR_RANGE = 2
GROUND_MOVE_ENERGY = 1.0

# experiment modes
GROUND_ONLY = "ground_only"
CONSTANT_DRONE = "constant_drone"
LIMITED_DRONE = "limited_drone"
EXPERIMENT_MODE = LIMITED_DRONE

# drone deployment
DRONE_DEPLOY_STEP = 10
MAX_DRONE_DEPLOYMENTS = 3
DRONE_REDEPLOY_COOLDOWN = 5

# down facing camera
DRONE_SENSOR_RANGE = 5

# drone movement
DRONE_CRUISE_ALTITUDE = 2.0
DRONE_VERTICAL_SPEED = 1.0
DRONE_CLEARANCE = 1.0
DRONE_SCAN_STEPS = 2

# forward camera
FORWARD_CAMERA_RANGE = 4
FORWARD_CAMERA_HALF_ANGLE_DEGREES = 30.0

# drone energy per simulation step
DRONE_TAKEOFF_ENERGY = 4.0
DRONE_FLIGHT_ENERGY = 2.0
DRONE_SCAN_ENERGY = 1.5

# simulation
MAX_SIMULATION_STEPS = 1000
VISUALIZATION_DELAY = 0.1