MAP_FILE = "maps/map4.txt"

# cell values
UNKNOWN = -1
FREE = 0
OBSTACLE = 1

# ground robot
ROBOT_SENSOR_RANGE = 2
GROUND_MOVE_ENERGY = 1.0

# experiment modes
GROUND_ONLY = "ground_only"
CONSTANT_DRONE = "constant_drone"
SMART_DRONE = "smart_drone"
EXPERIMENT_MODE = GROUND_ONLY

# simulation
MISSION_TIME_LIMIT = 200.0
EXPLORATION_COMPLETE_PERCENT = 95.0
VISUALIZATION_DELAY = 0.01

SIMULATION_STEP_SECONDS = 1.0

MAX_SIMULATION_STEPS = int(
    MISSION_TIME_LIMIT / SIMULATION_STEP_SECONDS
)

# drone deployment
DRONE_SPEED = 3
DRONE_DEPLOY_STEP = 10
DRONE_REDEPLOY_COOLDOWN = 5
MIN_GROUND_STEPS_BETWEEN_DEPLOYMENTS = 8
if EXPERIMENT_MODE == CONSTANT_DRONE:
    DRONE_REDEPLOY_COOLDOWN = 3
    MIN_GROUND_STEPS_BETWEEN_DEPLOYMENTS = 3

# down facing camera
DRONE_SENSOR_RANGE = 5

# drone movement
DRONE_CRUISE_ALTITUDE = 2.0
DRONE_VERTICAL_SPEED = 1.0
DRONE_CLEARANCE = 1.0
DRONE_SCAN_STEPS = 2

# forward camera
FORWARD_CAMERA_RANGE = 4
FORWARD_CAMERA_HALF_ANGLE_DEGREES = 30.0

# drone energy per simulation step
DRONE_TAKEOFF_ENERGY = 4.0
DRONE_FLIGHT_ENERGY = 2.0
DRONE_SCAN_ENERGY = 1.5

# smart deployment
SMART_DEPLOYMENT_THRESHOLD = 12.0
FRONTIER_COUNT_WEIGHT = 0.4
FRONTIER_DISTANCE_WEIGHT = 1.0
UNKNOWN_PERCENT_WEIGHT = 0.08
NO_PROGRESS_WEIGHT = 4.0
DRONE_DEPLOYMENT_COST = 5.0
PROGRESS_WINDOW = 8
MIN_PROGRESS_PERCENT = 2.0
DRONE_INFORMATION_GAIN_WEIGHT = 2.0
DRONE_DISTANCE_WEIGHT = 0.5
DRONE_INFORMATION_RADIUS = 3